### PR TITLE
Conversational AI Design Guidance doc is created

### PR DESCRIPTION
**Pull request by ikivanc**
Conversational AI Design Guidance doc is created

### CODE REVIEW

**Review by stephanbisser — APPROVED** [review]

**Comment by stephanbisser** [comment]
Thanks a lot!

**Comment by arafattehsin** [comment]
Thanks Ibrahim. This looks great. I have one suggestion on this. 

As this is the root of Community Docs, do you think that it should have the folder structure like this as below or we should only focus on the design part in these docs?

**Design**
	_Infographics
	Guidelines
	Patterns
	..._		
**Develop**
	_Implement the Bot Builder Middleware
	..._
**Debug** 	
	_Testing Guidelines 
	Emulator
	Chatdown / Transcript 
	..._
**Deploy**
	_Continuous Integration
	..._
**Manage**
	_Analytics 
	..._

This way, we will also be aligned with the Official Docs and I think we will have more flexibility to add some more content. 

Your thoughts please @garypretty @jamesemann @szul @ikivanc @cloudguy-pro ?

**Comment by arafattehsin** [comment]
cc: @garypretty @szul @jamesemann

**Comment by garypretty** [comment]
@arafattehsin This sounds like a good approach to me.

**Comment by stephanbisser** [comment]
I now created the folder structure as proposed by @arafattehsin 
@ikivanc could you please add your guidelines to Design/Guidelines then?

**Comment by ikivanc** [comment]
Created another pull request, you can ignore this. @arafattehsin @garypretty @cloudguy-pro

**Pull request closed without merging**
